### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by kedeger**
navbar style changes/fixes, homepage description color/size text change.

### CODE REVIEW

**Comment by ChrisKenyon79** [comment]
Code looks good. SOMEONE ATE THEIR WHEATIES WITH SOY TODAY

**Comment by jmduhon** [comment]
YAH!!!!!!

**Comment by kedeger** [comment]
💯 \* 👍  \* 💯

**Comment by zmcdaniel** [comment]
👍 🙇

**Pull request merged**
